# Requires a parent test stage

build:
  stage: build
  image: node:latest
  tags:
    - aws-docker

  except: # this will not work when $RUN_BVT is true
    variables:
      - $RUN_BVT == "true"

  before_script:
  script:
    - npm install --progress=false
    - npm run build

  cache:
    paths:
      - node_modules/

  artifacts:
    expire_in: 1 week
    paths:
      - dist
