default:
  tags:
    - prod

variables:
  PROJECT_SLUG: "{{ cookiecutter.project_slug }}"

stages:
  - .pre
  - test
  #- build
  #- deploy
  #- .post

# This job will only run if you've supplied a ACCESS_TOKEN
# It will make the changes to the template and create a Merge Request
# Attempted to use a cookiecutter docker image but they were old and was also getting unicode errors.
setup project:
  image: registry.gitlab.com/company/cli:2.7.6
  stage: .pre
  rules:
    - if: $ACCESS_TOKEN
  before_script:
    - asdf local python 3.7.5
    - pip3 install cookiecutter -q
    - asdf reshim python
    - apt-get update && apt-get install -y git rsync
    - git config --global user.email '${GITLAB_USER_EMAIL}'
    - git config --global user.name '${GITLAB_USER_ID}'
    - git remote set-url origin https://${GITLAB_USER_LOGIN}:${ACCESS_TOKEN}@$CI_SERVER_HOST/$CI_PROJECT_PATH.git
    - git checkout -b setup-$CI_JOB_ID
  script:
    # Use case: template files and cookiecutter.json in root
    - cookiecutter --version
    - rsync -a --exclude '.git' . "/tmp/{{ cookiecutter.project_slug }}"
    - cp "/tmp/{{ cookiecutter.project_slug }}/cookiecutter.json" /tmp/
    - echo "Will be creating /tmp/${CI_PROJECT_NAME}"
    - ls -l "/tmp/{{ cookiecutter.project_slug }}"
    - cookiecutter --no-input / --directory tmp -o /tmp/ product_name=${CI_PROJECT_NAME}
    # Replaces files from template
    - cp -Rf "/tmp/$CI_PROJECT_NAME/." .
    - git status
    # Stage and push new branch
    - git add . && git commit -m "Updating project with parameters." && git push -u origin setup-$CI_JOB_ID -o merge_request.create -o merge_request.target=main -o merge_request.title="Initial configuration"

lint:
  image: node:14.14.0-alpine
  stage: test
  script:
    - yarn lint
  allow_failure: true